import { CronJob } from 'cron';
import Audio from '#/models/audio';
import AutoGeneratedPlaylist from '#/models/autoGeneratedPlaylist';




const generatedPlaylist = async () => {
    const result = await Audio.aggregate([
        {$sort: {likes: -1}},
        {$sample: {size: 20}},
        {$group: {
            _id: "$category",
            audios: {$push: "$$ROOT._id"}
        }},
    ])

    result.map(async (item) => {
        await AutoGeneratedPlaylist.updateOne(
            {title: item._id},
            {$set: {items: item.audios}},
            {upsert: true}
        )
    })

    return result

}

const job = new CronJob (
	'0 0 * * *',
	async function () {
		await generatedPlaylist()
	},
);