
import { UpdateFollowings, generateAutoPlaylist, getAutoGeneratedPlaylist, getFollowersProfile, getFollowersProfilePublic, getFollowingsProfile, getIsFollowing, getPlaylistAudios, getPrivatePlaylistAudios, getPublicPlaylist, getPublicProfile, getPublicUploads, getRecommendByProfile, getUploads } from "#/controllers/profile";
import { isAuth, mustAuth } from "#/middleware/auth";
import { Router } from "express";


const router = Router();

router.post('/update-followers/:profileId', mustAuth, UpdateFollowings)
router.get('/uploads', mustAuth, getUploads)
router.get('/uploads/:profileId', getPublicUploads)
router.get('/info/:profileId', getPublicProfile)
router.get('/playlist/:profileId', getPublicPlaylist)
router.get('/recommended', isAuth, getRecommendByProfile)
router.post('/auto-generated-playlist', mustAuth, generateAutoPlaylist)
router.get('/auto-generated-playlist', isAuth, getAutoGeneratedPlaylist)
router.get("/followers", mustAuth, getFollowersProfile)
router.get("/followers/:profileId", getFollowersProfilePublic)
router.get("/followings", mustAuth, getFollowingsProfile)
router.get("/playlist-audios/:playlistId", mustAuth, getPlaylistAudios)
router.get("/private-playlist-audios/:playlistId", mustAuth, getPrivatePlaylistAudios)
router.get("/is-following/:profileId", mustAuth, getIsFollowing)




export default router;